name: CI

on:
  push:
    branches:
    - master

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1
    - name: Build
      env:
        DOCKER_HUB: ${{ secrets.DKR_KEY }}
        DOCKER_HUB_KEY: ${{ secrets.DKR_TKN }}
      run: |
        echo 'Docker login'
        docker login -u $DOCKER_HUB -p $DOCKER_HUB_KEY
        echo 'Running build.....'
        docker build -t $DOCKER_HUB/echo-server .
        echo 'Pushing image...'
        docker push $DOCKER_HUB/echo-server
        echo 'Done!!!!'
